[tool.pytest]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = ["Test*", "*Test"]
python_functions = "test_*"

[tool.pytest.ini_options]
markers = [
    "unit: marks a test as a unit test",
    "integration: marks a test as an integration test",
    "slow: marks a test as slow",
]
pythonpath = ["."]