# Testing environment configuration
env: testing
debug: false
version: "0.1.0"

# API configurations
api:
  openai:
    # API key should be in environment variables or .env file
    model: "gpt-3.5-turbo"  # Use cheaper model for testing
    max_tokens: 500
    temperature: 0.7
    timeout: 30
  
  anthropic:
    # API key should be in environment variables or .env file
    api_url: "https://api.anthropic.com/v1/messages"
    model: "claude-3-haiku-20240307"  # Use cheaper model for testing
    max_tokens: 500
    temperature: 0.7
    timeout: 30
  
  perplexity:
    # API key should be in environment variables or .env file
    api_url: "https://api.perplexity.ai/chat/completions"
    model: "sonar"
    max_tokens: 500
    temperature: 0.2
    timeout: 30

# Cache settings
cache:
  enabled: false  # Disable cache for testing to ensure fresh results
  ttl: 300  # 5 minutes in seconds
  directory: "~/.vinkeljernet/test_cache"
  max_size_mb: 10

# Logging configuration
logging:
  level: "INFO"
  file: "vinkeljernet_test.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console: true

# Application settings
app:
  interface: "cli"
  default_profile: "dr_profil"
  profile_directory: "tests/fixtures/profiles"
  results_directory: "tests/fixtures/results"
  default_output_format: "json"
  num_angles: 3  # Fewer angles for testing

# Extra settings for testing
extra:
  testing:
    mock_api_responses: true
    use_fixtures: true
    verify_angles_structure: true