# Development environment configuration
env: development
debug: true
version: "0.1.0"

# API configurations
api:
  openai:
    # API key should be in environment variables or .env file
    model: "gpt-4"
    max_tokens: 1000
    temperature: 0.7
    timeout: 60
  
  anthropic:
    # API key should be in environment variables or .env file
    api_url: "https://api.anthropic.com/v1/messages"
    model: "claude-3-opus-20240229"
    max_tokens: 1000
    temperature: 0.7
    timeout: 60
  
  perplexity:
    # API key should be in environment variables or .env file
    api_url: "https://api.perplexity.ai/chat/completions"
    model: "sonar"
    max_tokens: 1000
    temperature: 0.2
    timeout: 60
    extra_options:
      top_p: 0.9
      return_images: false
      return_related_questions: false

# Cache settings
cache:
  enabled: true
  ttl: 3600  # 1 hour in seconds
  directory: "~/.vinkeljernet/cache"
  max_size_mb: 100

# Logging configuration
logging:
  level: "DEBUG"  # DEBUG for development
  file: "vinkeljernet.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console: true

# Application settings
app:
  interface: "cli"  # cli, web, or both
  default_profile: "dr_profil"
  profile_directory: "config"
  results_directory: "results"
  default_output_format: "markdown"
  num_angles: 5

# Extra settings
extra:
  dev_features:
    enable_experimental: true
    force_cache_refresh: false